# Generated by Django 4.2.30 on 2026-05-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_sitesetting_section_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('seo_audit_request', 'SEO Audit Request'), ('project_inquiry', 'Project Inquiry')], default='project_inquiry', max_length=32)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('won', 'Won'), ('lost', 'Lost / Closed')], default='new', max_length=16)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('project_type', models.CharField(blank=True, max_length=120)),
                ('budget', models.CharField(blank=True, max_length=60)),
                ('brief', models.TextField(blank=True)),
                ('site_url', models.URLField(blank=True, max_length=400)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('referrer', models.URLField(blank=True, max_length=400)),
                ('notes', models.TextField(blank=True, help_text='Internal notes from follow-ups.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'status'], name='website_lea_kind_1531be_idx'), models.Index(fields=['-created_at'], name='website_lea_created_307ff2_idx')],
            },
        ),
    ]
