# Generated by Django 4.2.30 on 2026-05-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL slug — kebab-case, no spaces.', max_length=140, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=240)),
                ('tag', models.CharField(default='Insights', help_text='Category badge shown above the title.', max_length=60)),
                ('excerpt', models.TextField(help_text='2-line summary used on the listing page and OG preview.', max_length=320)),
                ('body', models.TextField(help_text='Full post body in HTML. Use h2, h3, p, ul, ol, blockquote, pre, code, a, strong, em.')),
                ('cover_emoji', models.CharField(blank=True, default='✦', help_text='Decorative glyph rendered into the cover art tile if no image.', max_length=10)),
                ('read_minutes', models.PositiveIntegerField(default=6)),
                ('author_name', models.CharField(default='Yash Gupta', max_length=120)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['is_published', '-published_at'], name='website_blo_is_publ_daccbd_idx')],
            },
        ),
    ]
