# Generated by Django 4.2.30 on 2026-07-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_seed_commercial_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='kind',
            field=models.CharField(choices=[('seo_audit_request', 'SEO Audit Request'), ('project_inquiry', 'Project Inquiry'), ('subscription_inquiry', 'Subscription Inquiry')], default='project_inquiry', max_length=32),
        ),
    ]
